spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/bootex
    username: bootuser
    password: bootuser
    driver-class-name: org.mariadb.jdbc.Driver
  mvc:hiddenmethod:fileter:enable : true
  servlet:
    multipart:
      enabled: true
      location: C:\\upload
      max-request-size: 30MB
      max-file-size: 10MB

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  thymeleaf:
    cache: false

logging:
  level:
    org.hibernate.SQL : debug
    org.hibernate.type: trace

#org:
#  zerock:
#    upload:
#      path: C:\\upload
project:
  shop:
    upload:
      path: C:\\projectUpload


